base:
    data_name: outbrain
    data_format: csv
    data_root: C:/PytorchCTR/outbrain/
    feature_cols: {
        sparse_features: {
            name: [display_id, ad_id, ad_document_id, campaign_id, advertiser_id,
            event_document_id, platform_x, geo_location_x, source_id_admeta, publisher_id_x,
            source_id_eventmeta, publisher_id_y, category_id, entity_id, document_id_y,
            timestamp, platform_y, geo_location_y, traffic_source, new_session,
            publish_time_admeta_year, publish_time_admeta_month,
            publish_time_eventmeta_ts, publish_time_eventmeta_year,
            publish_time_eventmeta_month, event_timestamp_ts,
            uuid, document_id_x, document_id_ent, publish_time_admeta_ts],
            dtype: int
        },
        dense_features: {
            name: [confidence_level, confidence_level_ent, time_diff],
            dtype: float
        }
    }    
    label_col: {dtype: int, name: clicked}
    min_categr_count: 1
    test_data: C:/PytorchCTR/outbrain/test.csv
    train_data: C:/PytorchCTR/outbrain/train.csv
    valid_data: C:/PytorchCTR/outbrain/valid.csv
    use_valid: True
    dense_emb: True
    scaler: MinMaxScaler
